{
 "title": "Ray metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Worker Register Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Register Time Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ray_worker_register_time_ms_bucket"
    }
   ]
  },
  {
   "title": "Register Time Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ray_worker_register_time_ms_count"
    }
   ]
  },
  {
   "title": "Register Time Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ray_worker_register_time_ms_sum"
    }
   ]
  },
  {
   "title": "Unintentional Worker Failures Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ray_unintentional_worker_failures_total"
    }
   ]
  },
  { "title": "Spill Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "ray_spill_manager_objects" }
   ]
  },
  {
   "title": "Objects bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ray_spill_manager_objects_bytes"
    }
   ]
  },
  {
   "title": "Request Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ray_spill_manager_request_total"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Failed Worker Startup Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "ray_scheduler_failed_worker_startup_total"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    { "expr": "ray_scheduler_tasks" }
   ]
  },
  {
   "title": "Unscheduleable Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "ray_scheduler_unscheduleable_tasks"
    }
   ]
  },
  { "title": "Raylet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "ray_raylet_cpu" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    { "expr": "ray_raylet_mem" }
   ]
  },
  { "title": "Push Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    { "expr": "ray_push_manager_chunks" }
   ]
  },
  {
   "title": "In-flight Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "ray_push_manager_in_flight_pushes"
    }
   ]
  },
  {
   "title": "Pull Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Bundles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "ray_pull_manager_active_bundles"
      }
     ]
    },
    {
     "title": "Requested Bundles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "ray_pull_manager_requested_bundles"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "targets": [
      { "expr": "ray_pull_manager_requests" }
     ]
    },
    {
     "title": "Retries Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "targets": [
      { "expr": "ray_pull_manager_retries_total" }
     ]
    },
    {
     "title": "Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "ray_pull_manager_usage_bytes" }
     ]
    }
   ]
  },
  { "title": "Process Startup Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Bucket",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_process_startup_time_ms_bucket"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "ray_process_startup_time_ms_count"
    }
   ]
  },
  {
   "title": "Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "ray_process_startup_time_ms_sum"
    }
   ]
  },
  { "title": "Outbound Heartbeat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Size Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "ray_outbound_heartbeat_size_kb_bucket"
    }
   ]
  },
  {
   "title": "Size Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_outbound_heartbeat_size_kb_count"
    }
   ]
  },
  {
   "title": "Size Sum",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_outbound_heartbeat_size_kb_sum"
    }
   ]
  },
  {
   "title": "Object Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fallback Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "ray_object_store_fallback_memory"
      }
     ]
    },
    {
     "title": "Local Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "ray_object_store_num_local_objects"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "ray_object_store_available_memory"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "targets": [
      { "expr": "ray_object_store_used_memory" }
     ]
    }
   ]
  },
  {
   "title": "Object Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pull Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "ray_object_manager_num_pull_requests"
      }
     ]
    },
    {
     "title": "Received Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "ray_object_manager_received_chunks"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Directory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Added Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "ray_object_directory_added_locations"
      }
     ]
    },
    {
     "title": "Lookups",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "targets": [
      { "expr": "ray_object_directory_lookups" }
     ]
    },
    {
     "title": "Removed Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "ray_object_directory_removed_locations"
      }
     ]
    },
    {
     "title": "Subscriptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "targets": [
      {
       "expr": "ray_object_directory_subscriptions"
      }
     ]
    },
    {
     "title": "Updates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      { "expr": "ray_object_directory_updates" }
     ]
    }
   ]
  },
  {
   "title": "Operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "ray_operation_queue_time_ms" }
     ]
    },
    {
     "title": "Run Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "ray_operation_run_time_ms" }
     ]
    },
    {
     "title": "Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_operation_count" }
     ]
    },
    {
     "title": "Active Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_operation_active_count" }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "targets": [
      { "expr": "ray_node_cpu_count" }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "targets": [
      { "expr": "ray_node_cpu_utilization" }
     ]
    },
    {
     "title": "Disk Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "targets": [
      { "expr": "ray_node_disk_free" }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "targets": [
      { "expr": "ray_node_disk_usage" }
     ]
    },
    {
     "title": "Disk Utilization %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ray_node_disk_utilization_percentage"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_node_mem_available" }
     ]
    },
    {
     "title": "Memory Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_node_mem_total" }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_node_mem_used" }
     ]
    },
    {
     "title": "Network Receive Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_node_network_receive_speed" }
     ]
    },
    {
     "title": "Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_node_network_received" }
     ]
    },
    {
     "title": "Network Send Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_node_network_send_speed" }
     ]
    },
    {
     "title": "Network Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_node_network_sent" }
     ]
    }
   ]
  },
  {
   "title": "Internal Num",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infeasible Scheduling Classes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ray_internal_num_infeasible_scheduling_classes"
      }
     ]
    },
    {
     "title": "Process Started",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ray_internal_num_processes_started"
      }
     ]
    },
    {
     "title": "Spilled Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "ray_internal_num_spilled_tasks" }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "targets": [
      { "expr": "ray_cluster_active_nodes", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Pending Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "targets": [
      { "expr": "ray_cluster_pending_nodes", "legendFormat": "{{pod}}" }
     ]
    }
   ]
  },
  { "title": "GCS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "GCS Update Resource Usage Time Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ray_gcs_update_resource_usage_time_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GCS Actors Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 88 },
   "targets": [
    { "expr": "ray_gcs_actors_count", "legendFormat": "{{ pod }} > {{ NodeAddress }}" }
   ]
  },
  {
   "title": "GCS Update Resource Usage Time Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ray_gcs_update_resource_usage_time_bucket"
    }
   ]
  },
  {
   "title": "GCS Placement Group Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 88 },
   "targets": [
    {
     "expr": "ray_gcs_placement_group_count",
     "legendFormat": "{{instance}} > {{pod}} > {{NodeAddress}}"
    }
   ]
  },
  {
   "title": "GCS Placement Group Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "ray_gcs_update_resource_usage_time_sum",
     "legendFormat": "{{instance}} > {{pod}} > {{NodeAddress}}"
    }
   ]
  },
  { "title": "gRPC Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Request Finished Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "ray_grpc_server_req_finished_total"
    }
   ]
  },
  {
   "title": "Request Handling Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "targets": [
    {
     "expr": "ray_grpc_server_req_handling_total"
    }
   ]
  },
  {
   "title": "Request New Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 105 },
   "targets": [
    { "expr": "ray_grpc_server_req_new_total" }
   ]
  },
  {
   "title": "Request New Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ray_grpc_server_req_process_time_ms"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Report Bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "ray_heartbeat_report_ms_bucket" }
     ]
    },
    {
     "title": "Report Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "ray_heartbeat_report_ms_count" }
     ]
    },
    {
     "title": "Report Sum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "ray_heartbeat_report_ms_sum" }
     ]
    }
   ]
  }
 ]
}