kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podsa
  namespace: spacebeaver
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podsa
  namespace: spacebeaver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsa
  namespace: spacebeaver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsa
subjects:
- kind: ServiceAccount
  name: podsa
  namespace: spacebeaver
