version: '3.8'

volumes:
  data: {}
  broker: {}
  cache: {}
  node: {}
  outside_db: {}

services:
  app:
    build:
      context: ..
      dockerfile: compose/build/Dockerfile
      target: local
    volumes:
      - ../src:/app
    shm_size: 128m
    environment:
      __ENV__: Local
      ENVIRONMENT: "development"
      SECRET_KEY: d7b24a10f65b4cae8549d79991ebaf2b
      DOMAIN: 0.0.0.0:8000
      SSL: 'off'
      DATA_NETLOC: postgresql://local:local@data:5432/local
      CACHE_NETLOC: redis://cache:6379/0
      BROKER_NETLOC: amqp://broker:5672
      STATIC_URL: /static/
      MEDIA_URL: /media/
      SENTRY_DSN_BACKEND: ""
      SENTRY_DSN_FRONTEND: ""
      OUTSIDE_DATA_NETLOC: mysql+pymysql://root:root@outside_db:3306/test
      STRIPE_LIVE_SECRET_KEY: "sk_test_51L0TbIEteaLPKQxIHpYbrPvbEifBxUUF5hvd5mQRYKDYkQva1OizXalzZEDTJx2ktNz5EELbgLIwqgatxzdE99at00GsOOSOa8"
      STRIPE_TEST_SECRET_KEY: "sk_test_51L0TbIEteaLPKQxIHpYbrPvbEifBxUUF5hvd5mQRYKDYkQva1OizXalzZEDTJx2ktNz5EELbgLIwqgatxzdE99at00GsOOSOa8"
      STRIPE_LIVE_PUBLIC_KEY: "pk_test_51L0TbIEteaLPKQxIgGS4Xt728yADpXphrx8EdF0Fno0pFOEj5q4b7qM7kpFf6pj1lVxd8CQ0BR2iRwAhtsTk35ag00KjUbgSI6"
      STRIPE_TEST_PUBLIC_KEY: "pk_test_51L0TbIEteaLPKQxIgGS4Xt728yADpXphrx8EdF0Fno0pFOEj5q4b7qM7kpFf6pj1lVxd8CQ0BR2iRwAhtsTk35ag00KjUbgSI6"
      DJSTRIPE_WEBHOOK_SECRET: "whsec_080623b05d6e6f38ef6498392eaaacbae1308f5b652838d0a1cf3a0477274ed8" 
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - data
      - broker
      - cache
      - outside_db
      - stripe

  data:
    image: postgres:13.3
    shm_size: 500m
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local

  broker:
    image: rabbitmq:3.8-alpine
    volumes:
      - broker:/var/lib/rabbitmq

  cache:
    image: redis:6.2
    volumes:
      - cache:/data
    environment:
      MAX_MEMORY: 300mb
      MAX_MEMORY_POLICY: allkeys-lru

  outside_db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    volumes:
      - outside_db:/var/lib/mysql
      - ./outside_db/sms_item_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  
  stripe:
    image: stripe/stripe-cli:v1.7.4
    command: listen --forward-to http://app:8000/djstripe/webhook/
    environment:
      - STRIPE_API_KEY=sk_test_51L0TbIEteaLPKQxIHpYbrPvbEifBxUUF5hvd5mQRYKDYkQva1OizXalzZEDTJx2ktNz5EELbgLIwqgatxzdE99at00GsOOSOa8
      - STRIPE_DEVICE_NAME=djstripe_docker
