# Generated by Django 3.2.13 on 2022-05-12 10:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blockednumber'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blockednumber',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
