name: Build and test

on:
  push:
    branches:
    - '**'
    - '!branch-*.*'

jobs:
  # Build: build spark-testing-base and run the tests for specified modules.
  build:
    # Ubuntu 20.04 is the latest LTS. The next LTS is 22.04.
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup project dir env
      run: export CI_PROJECT_DIR=$(pwd)
    - name: Try and set compose interactive
      run: export COMPOSE_INTERACTIVE_NO_CLI=1
    - name: Bring up the project
      run: make up
    - name: Run the tests
      run: make test
