# Generated by Django 3.2.13 on 2022-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220502_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
