# Generated by Django 3.2.13 on 2022-05-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_complete_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twillion_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
