# Generated by Django 3.2.13 on 2022-05-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220506_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='complete_onboarding',
        ),
    ]
