# Generated by Django 3.2.13 on 2022-05-12 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220503_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('user', models.ManyToManyField(related_name='blocked_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
